### ISSUE TITLE
Pyro taking a lot of resources of my CPU and GPU

### ISSUE THREAD

**Issue by rockeZZergon** [pyroclient/pyro#111]
Tested on 2b2tpvp.net
![image](https://user-images.githubusercontent.com/64991049/89618937-bc5a9080-d895-11ea-9537-9fb62d70b1b7.png)
![image](https://user-images.githubusercontent.com/64991049/89619083-02175900-d896-11ea-93a5-51cb57139a0f.png)
2b2t end dimension
![image](https://user-images.githubusercontent.com/64991049/89619455-a4374100-d896-11ea-990f-96dea892a62d.png)
Staying at single base on 2b2t
![image](https://user-images.githubusercontent.com/64991049/89619843-5a028f80-d897-11ea-849e-108e0a619dc2.png)

**Comment by Artamedes** [comment]
Fixed in Alpha
