### ISSUE TITLE
Loader stuck on Initializing 

### ISSUE THREAD

**Issue by r-33** [pyroclient/pyro#125]
i had this issue where no matter how many times i restarted it would indefinantly be on initializing. Once i deleted all my pyro files and ran the launcher again it worked. But now my config is gone.

**Comment by TerikKek** [comment]
copy your config

**Comment by Artamedes** [comment]
Next time you can try only deleting the launcher.json

**Comment by TerikKek** [comment]
that worked for thx atramedes
