### ISSUE TITLE
Better offhandsystem, logoutspots, chat box remover and faster autotrap and holefill

### ISSUE THREAD

**Issue by Tolon131** [pyroclient/pyro#133]
offhandsystem like salhack so I can use offhandcrystal and switch to offhandgap at the saame time. Faaster autotrap idk seems kinda slow compaared to other clients, logoutpsots aaa chaatboxremover or some chat modules would be nice aaand same with holefill

**Comment by Artamedes** [comment]
Suggestions in separate issues. please.
