### ISSUE TITLE
Add Profiles

### ISSUE THREAD

**Issue by Tri-tan** [pyroclient/pyro#141]
On different servers you need different configs for different modules. Like on 2bPvP and 2b2t you want diffent configs. I suggest adding profiles, something like you can make profiles, save them and then load them. For instance i would be able to make a profile for 2bpvp and for 2b. then when playing on 2b i would load the 2b profile and it would use my saved settings. I could then log onto 2bpvp load my 2bpvp profile and use my configs for 2bpvp. If youve ever used vape (1.8.9 cheat client) you know what i mean.

**Comment by GiantNuker** [comment]
duplicated so many times lol
