### ISSUE TITLE
scale setting breaking clickgui

### ISSUE THREAD

**Issue by real-F-00** [pyroclient/pyro#149]
the scale option set to "0.5" in the clickgui module appears to cause weird stuff inside the clickgui, when dragging around window they shake really fast and if you are not careful they might go off-screen some widnows are just hard to click, and some clickgui feature just out right don't work, such as the color changer in various modules using it, (crystalaura, clickgui, ecc...) the only thing working 100% about the color changer is the color temperature or whatever it's called, it's the thing at the left or whatever, the option that actually allows you to change the color is just **not clickable**

some useful info:

screen resolution: 1280x720
minecraft gui scale: normal
forge version: 1.12.2-forge1.12.2-14.23.5.2768
max allocated RAM: 1600MB
no other mods appear to be conflicting with the issue
i tested with other clients, and without other clients (only pyro).

**Comment by GiantNuker** [comment]
Tested on 0.3 gui scale. It appears a few mouse events aren't scaled properly. Adding this to the bugfix list
https://cdn.nuker.dev/b2c5c204f9014ecf93a2c01717676c85.png
