### ISSUE TITLE
[BUG] packetmine normal doesnt work 

### ISSUE THREAD

**Issue by Ace8Underscore** [pyroclient/pyro#200]
**Describe the bug**

**To Reproduce**
1. Turn on module: '...'
2. Set the setting to 'normal .01 .80'
3. doesnt break the block early like it should

**Expected behavior**
send a break packet or something so the block breaks at 80% instead of 100%

**Screenshots**
Add screenshots or videos to help explain the problem.

**Additional context**

**Comment by Artamedes** [comment]
Fixed in dev.
