### ISSUE TITLE
[BUG] Jesus

### ISSUE THREAD

**Issue by Ace8Underscore** [pyroclient/pyro#201]
**Describe the bug**

**To Reproduce**
1. Turn on module: '...'
2. Set the setting to 'Solid Strict'
3. See error

**Expected behavior**
when toggled the player should be elevated to the top of the block so the player can walk on water
**Screenshots**
Add screenshots or videos to help explain the problem.

**Additional context**
when hugging a block in like a corner of two blocks the jesus wont go but sits there
another issue is where the jesus happens on the block below 
so instead of doing jesus at the ocean level at 63 like its supposed to for some reason its doing it at 62 one block below the top

**Comment by Artamedes** [comment]
Fixed in dev
