### ISSUE TITLE
[SUGGESTION] autofish

### ISSUE THREAD

**Issue by ddev8888** [pyroclient/pyro#208]
**Is your feature request related to a problem? Please describe.**
im trying to mend my amor but since i dont wanna waste much resources by splashing xp bottles on anarchy servers i try to auto fish but i dont wanna use other clients for this.

**a non enchanted fishing rod brings as much loot as a maxed on**
if possible could u add the loot falue of the fishing rod without enchantments as high as a maxed out one so that youre only getting fish/books/tools the good stuff. (only if possible)

**if the request above isnt possible**
then i would be happy to at least have an autofisher

**Additional context**
as always im happy to improve the client and help with suggestions bug reports or donations if needed

**Comment by Artamedes** [comment]
Added in dev.
