### ISSUE TITLE
A option to save configs and switch between them

### ISSUE THREAD

**Issue by ghost** [pyroclient/pyro#214]
An option to switch between saved configs (keybinds, settings, and toggles modules) would be great I hate switching my crystal aura settings, speed settings and elytra fly settings every time I connect to another server

I option to save your config and toggle between them would be pretty helpful and I don't think would be to hard to add

**Comment by ddev8888** [comment]
How would you safe this for example? Like try to tell the devs an option on how to display/safe the settings with a password or code or idk give a clue on how you would add it cause depending on how many servers u play on this could be really difficult

**Comment by ghost** [comment]
> How would you safe this for example? Like try to tell the devs an option on how to display/safe the settings with a password or code or idk give a clue on how you would add it cause depending on how many servers u play on this could be really difficult

no just like configs in txt files that you can switch between so you don't have to change all your settings for another server

**Comment by ghost** [comment]
> How would you safe this for example? Like try to tell the devs an option on how to display/safe the settings with a password or code or idk give a clue on how you would add it cause depending on how many servers u play on this could be really difficult

like you make a config with a bunch of settings and keybinds for modules save it and later you can switch back to that same config with all the same settings and keybinds you saved on that config

**Comment by Papa-Quill** [comment]
Make it be something like:

$prefix save (prefix
then if you want to load
$prefix load (prefix)
If you wanna delete one
$prefix del (prefix)

**Comment by GiantNuker** [comment]
been suggested a lot, in dev
