### ISSUE TITLE
[SUGGESTION] auto 32k 

### ISSUE THREAD

**Issue by ddev8888** [pyroclient/pyro#215]
**Describe the solution you'd like**
Basically a good working auto 32k that places hoppers and a shulk in seconds and auto takes out the sword for u 

**Describe alternatives you've considered**
If that auto pulk sword out aint working then at least a good and fast hopper+shulker placement 

**Additional context**
As always im trying to improve the client by suggesting new stuff and reporting bugs or donating

**Comment by Rayyan585** [comment]
tbh 32k is useless on pretty much all servers - there's no point.
