### ISSUE TITLE
[SUGGESTION] phase

### ISSUE THREAD

**Issue by ddev8888** [pyroclient/pyro#217]
**Describe the solution you'd like**
an option that lets you glitch through blocks when turned on without taking dmg 
**Describe alternatives you've considered**
if the dmg taking cant be provended could you add an extra option to the phase module that autoeats when turned on? so that the dmg dealt is staying low
**Additional context**
as always im trying to improvethe client with new suggestions and bug reports or if needed donations

**Comment by Artamedes** [comment]
AutoEat will be implemented seperately
