### ISSUE TITLE
[SUGGESTION] Boatfly FixYaw

### ISSUE THREAD

**Issue by debuxxed** [pyroclient/pyro#218]
A lot of rubberbands caused because boat dont rotating together with user camera. I tested Pyro Boatfly together with Boatfly from Future Client, and turned on "FixYaw" in the Future, and i could to rotate it, and it was fine, but it caused one issue: Boat slipped, so i cant to fall or go up. 
I want you guys add FixYaw feature in Boatfly module

**Comment by GiantNuker** [comment]
Boatfly is updated in dev build and works fine on 2b now
