### ISSUE TITLE
GUI not Scrollable

### ISSUE THREAD

**Issue by ganguy** [pyroclient/pyro#235]
The size of the modules make it so some of the lower modules aren't on the screen. This makes it impossible to access those modules without going into video settings and making the entire Minecraft GUI small.
Please add a scroll feature so I don't have to do that every time.

**Comment by rdxxn** [comment]
$gui 0.8

**Comment by ghost** [comment]
Yep. They sure need to add Scrollable gui

**Comment by ghost** [comment]
I’ve told giant nuker in dms a while ago, he said “sure”. I think he has already taken this to note.

**Comment by Papa-Quill** [comment]
It will probably be fixed next update if not soon.
