### ISSUE TITLE
[SUGGESTION] FACE PLACE OVER-RIDE

### ISSUE THREAD

**Issue by HelpMopDog** [pyroclient/pyro#238]
**Is your feature request related to a problem? Please describe.**
Its kinda annoying when someone is at a health where ik how fast pyro can go where face placing would be a good option in the current moment but wont do to my min dmg
**Describe the solution you'd like**
Some sort of key that i can toggle that would allow my min dmg to become lower or somthing like that
**Describe alternatives you've considered**
Not really anything
**Additional context**

**Comment by Artamedes** [comment]
Ok I will add a key that can be held down that will deal OverrideMinDMG

**Comment by Artamedes** [comment]
Added in dev
