### ISSUE TITLE
[BUG] Trajectories Bug w Fishing Rod

### ISSUE THREAD

**Issue by Papa-Quill** [pyroclient/pyro#253]
**Describe the bug**
The module Trajectories has an issue with the Fishing Rod having incorrect pathing when over a 7 block distance, where the rod will not hit where the trajectory says it will.

**To Reproduce**
1. Turn on module: 'trajectories'
2. Set the setting to 'N/A'
3. See error

**Expected behavior**
Trajectories to be correct and show me where the rod will land.

**Screenshots**
https://cdn.discordapp.com/attachments/472223564796264448/749143168427229255/2020-08-29_00-32-05.mp4

**Additional context**
None needed.

**Comment by GiantNuker** [comment]
minecraft uses randoms to figure out where something will land, so we cant predict it exaclty
