### ISSUE TITLE
[BUG]Can't fly up after latest update/Fix from Kami /w Pyro

### ISSUE THREAD

**Issue by BumleDK** [pyroclient/pyro#255]
**Describe the bug**
Using Kami ElytraFlight works again after the latest fix, but is cause ElytraFlight with Pyro to break.
The AutoJump for takeOff doesn't work, or manual jump.
I have to have Kami ElytraFlight turned on with/without Pyro's to take off. Trying to fly up with only Pyro, but have Kami's loaded, is not possible. It is only possible to fly up, if i have Kami's active, if i choose to fly with Pyro's

**To Reproduce**
1. Having both Kami and Pyro loaded. 
2. Only turn on Pyro's is unable to take off, as before the problem occurred with the latest updates ´No problem or incompatibility issues has never been a thing before these latest updates.

**Expected behavior**
Expected outcome was, as it used to be, the ElytraFlight for both Kami and Pyro to work as they always has done ´Until latest few updates from Kami, causing problems with Pyro's flight, Which works just fine, if Kami is removed from mods folder´

**Screenshots**
A GIF is showing me using both to take off, then Kami's turned off, to show issue occurring with only Pyro's ElytraFlight active, but with kami in Mods folder.
https://puu.sh/Gn15K/a190810c1e.gif

My thought was Kami is the issue, so made a bug report (Which this i copy/paste of) to Kami devs, it got closed/invalid in 1 minute. Asked how and why, and i got these responds
https://puu.sh/Gn1pA/0ffe71c1fa.png

**Comment by GiantNuker** [comment]
Solved a while ago on kamis end
