### ISSUE TITLE
[BUG] Surround creating ghost blocks

### ISSUE THREAD

**Issue by REM0VED** [pyroclient/pyro#257]
**Describe the bug**
This has only happened to me three or four times while using Pyro however it is reasonably devasting to the performance of the client. Occasionally, in my experience, surround will create client side only blocks. Then someone can place crystaks from what looks like inside the block. However I cannot move to the middle to block space for the crystal entities because the ghost block has physcal presence for me.

**To Reproduce**
1. Turn on module: 'Surround'
2. Set the setting to 
![Pyro Surround Config](https://user-images.githubusercontent.com/68415938/91649602-10cde600-eab9-11ea-8675-e8c256d7a48e.PNG)

3. See error

https://drive.google.com/file/d/1Gub2OCwXIS00uAmTFZYaONzBXmxArZo9/view?usp=sharing

**Expected behavior**

**Screenshots**
Add screenshots or videos to help explain the problem.

**Additional context**

**Comment by Artamedes** [comment]
Fixed in 1.3 also you can use NoGlitchBlocks to prevent this from happening
