### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by LilN1gger** [pyroclient/pyro#261]
I was thinking for autobedbomb feature in pyro if you could recode auto trap but instead of obby make it beds but on their head y level, like say their feet was on y level 130 and they have surround on it would place a block infront of the surround and auto bed bomb on y level 131?

**Comment by u3o** [comment]
Thats autobedbombs buisness

**Comment by GiantNuker** [comment]
duplicated somewhere else but they wrote the issue better
