### ISSUE TITLE
[SUGGESTION] Make it so you can scroll up and down in the gui. Makes it so you can see the full thing even with a smaller screen

### ISSUE THREAD

**Issue by TheRedBlocker** [pyroclient/pyro#269]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GiantNuker** [comment]
Gui is going to be redesigned soon

**Comment by Papa-Quill** [comment]
Yes please a redesign would be so nice

**Comment by GiantNuker** [comment]
redesign soon
