### ISSUE TITLE
[BUG] When I launch minecraft it doesn't open

### ISSUE THREAD

**Issue by dez03** [pyroclient/pyro#271]
**Describe the bug**
When I press "play" to launch minecraft forge 1.12.2 literally nothing happens. the minecraft screen doesnt show up. i have asked other people and its a pyro thing. im not sure the cause, pyro launched perfectly fine until the update 1.13. i have launched it before in the new update but this problem has happened every so often. task manager says minecraft is open but i dont see it. it cant be what's in my mods folder because like i said, i have launched 1.13 pryo before

**To Reproduce**
1. it sometimes launches normally and im good
2. sometimes the bug happens

**Expected behavior**
i expect minecraft to launch but it doesnt sometimes 

**Screenshots**
none needed. it just doesnt launch but task manager said it did

**Additional context**
 nothing

**Comment by dotdivee** [comment]
yeah that happened to me today. just delete pyro.jar from your mods folder and redownload it from pyro.nuker.dev
