### ISSUE TITLE
[BUG] i cant even run the client

### ISSUE THREAD

**Issue by jimbo400** [pyroclient/pyro#272]
i like it how the installer doesnt work ezzzzzz pyro on top totally worth 20 dollars ezzzzzzzzzzzzzzzzzzz totally not salhack paste with maybe 1 unique module ezzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by TediousDuskFall** [comment]
I already asked you multiple times if you wanted to team up against pyro but you said no so why are u complaining *shrug*
