### ISSUE TITLE
[BUG] Auto reconnnect issue

### ISSUE THREAD

**Issue by Frosty003** [pyroclient/pyro#281]
**Describe the bug**
When you are using another client with pyro that has auto reconnect the auto reconnects appear on top of eachother

**Expected behavior**

**Screenshots**
https://cdn.discordapp.com/attachments/747461797119787084/751390164504543282/problem.jpg
**Additional context**
I don't know if you can fix this but if in a update you can make a module that enable/disables this that would be nice ty.

**Comment by Artamedes** [comment]
autoreconnect already allows you to disable showing the buttons
