### ISSUE TITLE
ALOT

### ISSUE THREAD

**Issue by DezzDox** [pyroclient/pyro#282]
FIX ELYTRAFLY2 ALWAYS BEING ON WHEN USING FUTURE AND PLEAS MAKE INTERTIA WORK WITH PYRO AND MAKE PACKET WITH INF DUR WORK WITH FUTURE

**Comment by Papa-Quill** [comment]
DO YOU KNOW HOW TO TURN OFF CAPS LOCK? I CAN'T FIND OUT HOW TO TURN OFF CAPS LOCK HELP!!1!!!!!1111

**Comment by ghost** [comment]
Ez
