### ISSUE TITLE
New Module I would like to see in pyro client

### ISSUE THREAD

**Issue by Frosty003** [pyroclient/pyro#285]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to see no skylight in pyro client because not many other clients have a working one

**Describe alternatives you've considered**
I could just use forgehax but I don't want to

**Additional context**
none needed

**Comment by xxxcodestation1** [comment]
Works for me

**Comment by GiantNuker** [comment]
Its in norender
