### ISSUE TITLE
[SUGGESTION] Load times

### ISSUE THREAD

**Issue by d2k11** [pyroclient/pyro#292]
**Is your feature request related to a problem? Please describe.**
The game takes way too long to load when loading Pyro.

**Describe the solution you'd like**
Get faster servers or a better CDN to serve the file faster (I have a 1GBPS network connection; it is not my network connection)

**Describe alternatives you've considered**
Killing myself

**Additional context**
N/A

**Comment by SonnyLikesCode** [comment]
YEAH FUCKING FIX THIS
