### ISSUE TITLE
[SUGGESTION]Good Modules Suggestion (bed aura)

### ISSUE THREAD

**Issue by crackcocacola** [pyroclient/pyro#293]
Add bed aura lile crystal aura, add it into the combat section, as well add "Custom chat" or "suffix" to flex pyro, also add crafting slots on inventory view! Thats all

**Comment by Papa-Quill** [comment]
Crafting slots are already in the hud.  A chat suffix suggestion has already been made by me here: https://github.com/pyroclient/pyro/issues/278
and bed aura is low priority right now as there are other very important things that the devs need to focus on.

**Comment by GiantNuker** [comment]
dupliocate
