### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by Flickz077** [pyroclient/pyro#296]
it would be nice to have a custom font for pyro client, its boring having the same boring pyro font

**Comment by IlNevioIl** [comment]
the summit font is nice

**Comment by Flickz077** [comment]
ye summit font is rly nice. ionar, get summit font and put it in pyro

**Comment by GiantNuker** [comment]
you can change the font to any ttf. put a file called `font.ttf` in the .minecraft/pyro folder - you can change spacings and stuff in `font.json`
