### ISSUE TITLE
Add Kill Aura

### ISSUE THREAD

**Issue by SmartAfrican03** [pyroclient/pyro#297]
There is an issue with Pyro Client.  There is simply no Kill Aura built in with Pyro Client.

I would like for the next update to add this in with Pyro.

If Kill Aura can't be added then maybe in a future update.
*Since Pyro is a utility and pvp client Kill Aura should definitely be added as Salhack already has that feature in already.*

**Comment by shaggyc9** [comment]
Pyro HAS a killaura module, it's called "aura".

**Comment by Artamedes** [comment]
Aura.
