### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by IlNevioIl** [pyroclient/pyro#298]
**Is your feature request related to a problem? Please describe.**
make different themes for the client

**Describe the solution you'd like**
ex: future theme: if this is enabled the client looks like futures gui

**Describe alternatives you've considered**
maybe sth like a resource pack so u can "design" the gui how u want it to be

**Additional context**
maybe do animated stuff too ex: fire in the background if gui is opened

**Comment by GiantNuker** [comment]
too much work, especially to make it configurable
