### ISSUE TITLE
[SUGGESTION] autopull for anchor

### ISSUE THREAD

**Issue by ddevil69gfg** [pyroclient/pyro#299]
**Describe the solution you'd like**
I would like another option for anchor. Its hould act like an constant pull towards the ground without toggling off and without being forced to turn it off by a key in order to jump out of a hole or even jumping in general. It shall act like it constantly pulls u down without a need of actual holes. Also without locking u on the ground so that u can Always jump. 

Please note that it shall not mess with airstrafe when turned on

**Comment by ghost** [comment]
There is a module called ReverseStep that already does this.

**Comment by GiantNuker** [comment]
Fall

**Comment by GiantNuker** [comment]
well thats kinda weird but dnger is right too
