### ISSUE TITLE
Shift Surround

### ISSUE THREAD

**Issue by freethemanatee** [pyroclient/pyro#302]
Just add an option to the surround named "Sneak Only", and would just toggle surround when you are shifting. Not a lot of people use sneak to toggle surround I just think its easier sometimes.

**Comment by GiantNuker** [comment]
you can bind it to whatever your sneak key is

**Comment by freethemanatee** [comment]
ya but its kinda chinese when you are lets say going down on an elytra maybe you want to toggle it off
