### ISSUE TITLE
[SUGGESTION] Menu scroll

### ISSUE THREAD

**Issue by d2k11** [pyroclient/pyro#307]
**Is your feature request related to a problem? Please describe.**
I want my scale to be nice and big, except some modules have so many options and go off screen.

**Describe the solution you'd like**
Add scroll wheel functionality to move the top of the menus up and down.

**Describe alternatives you've considered**
Moving scale down but looks like ass.

**Additional context**
N/A

**Comment by xxxmeh** [comment]
added in next version
