### ISSUE TITLE
[BUG] Turning on AutoPilot while not in a boat crashes you.

### ISSUE THREAD

**Issue by dngerr** [pyroclient/pyro#324]
**Describe the bug**
If you turn on AutoPilot while you aren't in a boat your game crashes.

**To Reproduce**
1. Do not be in a boat
2. Turn on AutoPilot.

**Expected behavior**
I thought it would just tell me "You need to be in a boat" or something

**Screenshots**
does this really need to be clipped

**Comment by GiantNuker** [comment]
we never tested this lol

**Comment by GiantNuker** [comment]
Fixed in 1.4.1
