### ISSUE TITLE
[SUGGESTION] autocrystal damage sync

### ISSUE THREAD

**Issue by wallhackz** [pyroclient/pyro#345]
an option for the ca to add delay so it waits with dealing damage until the server is ready. I dont really know how this would work and what settings it should have but phobos had it and with the right config the ca got way more efficient. If this would be done right the ca would waste way less crystals.

**Comment by ddevil69gfg** [comment]
use 1.4 ca its a bit slower but places alot better you can improve speed by using fastplace
(in case ur not already using 1.4
