### ISSUE TITLE
[BUG] Game crashes when attempting to open second window / client with pyro

### ISSUE THREAD

**Issue by Captain-S0L0** [pyroclient/pyro#354]
**Describe the bug**
When attempting to open another minecraft window, both windows with the exact same forge mods and pyro, the first window that was opened crashes instantly, and fails to even produce a crash log like minecraft would.

**To Reproduce**
1. Open 1 window
2. Open second window
3. First window crashes

**Expected behavior**
The first window should not crash.

**Screenshots**
[hs_err_pid12497.log](https://github.com/pyroclient/pyro/files/5298738/hs_err_pid12497.log)
This is the only "crash log" produced, but I don't think it will help.

**Additional context**
Running linux mint 18.3, perhaps some sort of program numbering / naming problem where the launcher chooses both java games instead of just 1?

**Comment by GiantNuker** [comment]
This one is fixed in dev. Started running arch myself
