### ISSUE TITLE
Server Profiles[SUGGESTION]

### ISSUE THREAD

**Issue by J3ww** [pyroclient/pyro#367]
**Is your feature request related to a problem? Please describe.**
Server Profiles
**Describe the solution you'd like**
Have a profile that automatically toggles certain modules on connect
**Describe alternatives you've considered**
N/A
**Additional context**
Copies Settings Of Modules too

**Comment by u3o** [comment]
It is already in client since 1.4 lol, use server-servername as name of the profile
