### ISSUE TITLE
[BUG] Pyro does not run together with Phobos

### ISSUE THREAD

**Issue by ABC-Const** [pyroclient/pyro#408]
Phobos is a private client, arguably the best in the game. A new version of it has recently been leaked. 
(link removed due to virus)

The game launches fine with pyro+phobos but you are unable to join servers.
An error message comes up with 'Internal Exception: java.lang.NoClassDefFoundError: net/minecraft/NettyCompressionDecoder' when you attempt to join a multiplayer server.

I want to use various features phobos has such as CA/Offhand/Tooltips/AutoArmour/Portal ESP/Trajectories/Packetmine/Skeleton and many more while continuing to use pyro. Please fix compatibility.

![image](https://user-images.githubusercontent.com/71958313/96405283-70788000-1224-11eb-8714-1ed7da77e2ef.png)

**Comment by supakeks** [comment]
Correct me if I'm wrong but this is an issue on Phobos' side, no client is compatible with it...
Also it wasn't leaked, the owners just made an announcement in the discord and just attached the jar file

UPDATE: It's a fucking rat reset your passwords and shit

**Comment by 5HT2** [comment]
:clown_face: this is a Phobos code issue, not an incompatibility issue.

**Comment by supakeks** [comment]
Well it's been 3 days since this "issue", I now recommend you to change all of your passwords lol
