### ISSUE TITLE
flying in liquids

### ISSUE THREAD

**Issue by xxxmeh** [pyroclient/pyro#41]
when i go to the water and i am flying it is stop me and i cannot fly but am forced to swim but other client go through water like fast and very zoom which i am wanting to have. i am liking going through the water and lava quickly but pyro is give limitation on fluid flying which make me very upsedt i am not know if is my settings or if i am pepega but i am not able flying in water

**Comment by altmancarter60** [comment]
+1

**Comment by dngerr** [comment]
+1

**Comment by GiantNuker** [comment]
done in efly2
