### ISSUE TITLE
Client has Invalid Hardware error

### ISSUE THREAD

**Issue by ShadowYokai** [pyroclient/pyro#414]
I have a Mac. I've had really bad FPS issues the last few days and there was an update for my system OS. 
I did the update this evening and when I returned to load up Pyro, I got "Your Hardware is Invalid" as a message on the Pyro loading screen. 

My OS is macOS Catalina version 10.15.7. 
I run Future with Pyro, but I have never had this kind of issue with any of my clients before, even with previous Mac updates I've done in the past. 
I don't know how to fix this or if the problem is in the process of being fixed.

<img width="393" alt="Screen Shot 2020-10-24 at 7 59 17 PM" src="https://user-images.githubusercontent.com/71287222/97097357-02bdc100-1635-11eb-8c5a-e00bb402a566.png">

**Comment by Artamedes** [comment]
Please contact us on discord to get hwid reset.
