### ISSUE TITLE
[SUGGESTION] continue to skid from other clients

### ISSUE THREAD

**Issue by pastimee** [pyroclient/pyro#416]
I really like how pyro skids from other clients, it's one of my favorite parts.

**Comment by Novola** [comment]
yo bro i agree

**Comment by ghost** [comment]
![image0](https://user-images.githubusercontent.com/71094070/100122461-4fcdc680-2e71-11eb-9c87-36fb936249ec.png)
look at this absolutely selfmade module

**Comment by ghost** [comment]
Pyro hatar! Artamedes dont like!
