### ISSUE TITLE
secret mine thing (on xulu and phobos only currently)

### ISSUE THREAD

**Issue by xxxmeh** [pyroclient/pyro#5]
uncochad and mtnl were showing me how they can break blocks instantly, they punch a block with their hand mining it as fast as a pickaxe, it breaks on their screen but not on the other persons screen, they are then able to tap the block, uncochad used a pickaxe for this and it breaks instantly for everyone in the server
they said they were only able to do this on one block at a time and I think they had to toggle a module or something to break the invisible blocks
if u find out how to do this that would be epic

**Comment by ionar2** [comment]
Instant mode in speedygonzales

**Comment by Tigermouthbear** [comment]
packet mode in no swing

**Comment by Artamedes** [comment]
Implemented in dev (set start damage to 1.0)
