### ISSUE TITLE
NoInteract

### ISSUE THREAD

**Issue by lorem-impsum** [pyroclient/pyro#55]
A module with the concept of disallowing the player to specific interactions. The two main modes I have in mind would be crystals and chests. 
With mode crystals the player would be unable to place crystals **manually** (an option could be added to lock automatic ca placements to but I'm not sure if that's useful since you can just turn off ca). This is especially useful for using offhand gap for example because you would still be able to eat while looking at blocks.
Mode chests would stop you from opening any type of chests. This is very useful when regearing with obsidian by building a tower of echests and breaking them. Could also be useful outside of PvP for example when making stashes with lots of chests on top of each other.

*Modes:*
"chests", "crystals", "both"
"mainhand", "offhand", "both"
Placement: "onlyAutomatic", "none" //this isn't that important for reasons explained above

**Comment by Artamedes** [comment]
Added in dev
