### ISSUE TITLE
StrengthDetector

### ISSUE THREAD

**Issue by lorem-impsum** [pyroclient/pyro#56]
Pretty self-explanatory, basically it would detect if someone drinks a strength potion. I have seen many implementations of this feature in other clients but I think it's only useful if it somehow marks enemies with a red box for example.
Timestamps would be a useful addition too. It would basically just display the time passed since the potion was drank.

*Modes:*
"chatMessages", "render", "both"
"timestamps": True/False
\+ maybe color options for render mode

**Comment by GiantNuker** [comment]
Timestamps are not possible, however there is strength detection on tooltips
