### ISSUE TITLE
ImgurUploader

### ISSUE THREAD

**Issue by lorem-impsum** [pyroclient/pyro#58]
It would upload screenshots taken to imgur automatically. Mode copy would copy the link of the uploaded image and mode chat would display it on the chat on the client side.

*Modes:*
"copy", "chat"

**Comment by MrHakan** [comment]
Yeah pls thats very useful

**Comment by Artamedes** [comment]
https://www.curseforge.com/minecraft/mc-mods/advanced-screenshot-uploader
