### ISSUE TITLE
ShulkerPreview but better

### ISSUE THREAD

**Issue by lorem-impsum** [pyroclient/pyro#68]
So basically it's just shulker preview but with some extra functionality that you rarely see in anarchy clients (although you can find this in some non anarchy clients). The extra functionality would be to have a toggleable option inside shulker preview to show the content of shulkers dropped on the ground (above the shulker) and an other option to show the content of shulkers that are in the hand of an entity (future can do this for example with it's .peek command), ofc once again above the entity.

**Comment by Artamedes** [comment]
So a 3d shulker preview over shulker entity items?

tooltips already allows you to middle click items in your inventory (shulkers, enderchests) to see a gui of the preview

**Comment by Artamedes** [comment]
added in dev
