### ISSUE TITLE
DamageRender

### ISSUE THREAD

**Issue by lorem-impsum** [pyroclient/pyro#69]
This would be a pretty straight forward module that is basically just adding a feature that is found in many other games. My idea for it is to have a slight red overly around the screen if you are damaged and depending on how much health you have it would have more opacity and would cover a larger area. This idea could later be expand with other render modes serving the same purpose.

See basically any other game for reference, like seriously every second game in existence uses this.

**Comment by Artamedes** [comment]
-> DamageHUD
